FPS = 60
ZOOM = 4
GAME_BOY_RESOLUTION = 160,144
RESOLUTION = GAME_BOY_RESOLUTION[0]*ZOOM, GAME_BOY_RESOLUTION[1]*ZOOM
BACKGROUND_COLOR = (247, 247, 247)
SHOW_RECT = False
SHOW_GRID = False
DEBUG_ACTIVATION = False

# Battle
TOP_STATUS_SIZE = 80,32
BOTTOM_STATUS_SIZE = 88,40
BATTLE_TILE_SIZE = BATTLE_TILE_WIDTH,BATTLE_TILE_HEIGHT = 8,8

# Overworld
MOVE_DURATION_IN_SECONDS = 1/4
MOVE_DURATION_IN_FRAMES = int(MOVE_DURATION_IN_SECONDS*FPS)
OVERWORLD_TILE_SIZE = OVERWORLD_TILE_WIDTH, OVERWORLD_TILE_HEIGHT = (16,16)

# Message
MESSAGE_BOX_GRID = 0,12,20,6
MESSAGE_TILE_SIZE = MESSAGE_TILE_WIDTH,MESSAGE_TILE_HEIGHT = 8,8
DELAY_BETWEEN_CHARS = 1
DELAY_FOR_SCROLLING = 6
AUTO_SCROLL_DELAY = 10
AUTO_SCROLL = False
