SHOW_RECT = False
SHOW_GRID = False
BACKGROUND_COLOR = (247, 247, 247)
ZOOM = 2
ORIGINAL_GAME_BOY_RESOLUTION = 160,144
TOP_STATUS_ORIGINAL_SIZE = 80,32
BOTTOM_STATUS_ORIGINAL_SIZE = 88,40
ORIGINAL_TILE_SIZE = ORIGINAL_TILE_WIDTH,ORIGINAL_TILE_HEIGHT = 8,8
TILE_SIZE = TILE_WIDTH,TILE_HEIGHT = ORIGINAL_TILE_WIDTH*ZOOM, ORIGINAL_TILE_HEIGHT*ZOOM


